config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'contact_files#index'

  resources :contacts, only: [:index, :new, :create]
  resources :contact_files, only: [:show,:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  PHONE_REGEX = /\A\(\+\d{2}\)\s\d{3}(\s|-)\d{3}(\s|-)\d{2}(\s|-)\d{2}\z/.freeze

  validates :name, :date_of_birth, :phone, :address, :credit_card_number, :credit_card_network, :email, presence: true
  validates :name, format: { with: /\A[^!@#\$%\^&*()+_=]+\z/ }
  validates :email, uniqueness: { scope: :user_id }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, format: { with: PHONE_REGEX, message: 'Invalid phone format' }

  encrypts :credit_card_number


  before_validation :normalize_date_of_birth

  private

  def key_provider
    ActiveSupport::KeyProvider.new(
      key: Rails.application.credentials.secret_key_base[0, 32],
      salt: Rails.application.credentials.secret_key_base[32, 32]
    )
  end

  def normalize_date_of_birth
    # TODO: Normalize the date_of_birth to the required format
  end
end

app/models/contact_file.rb
class ContactFile < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  enum status: [ :on_hold, :processing, :failed, :finished ]
  validates :file_name, presence: true
  validates :file, presence: true
  validates :status, presence: true

  serialize :error_messages, Array

  after_initialize :set_default_status, if: :new_record?

  private

  def set_default_status
    self.status ||= :on_hold
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
  has_many :contact_files

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @contact_files = current_user.contact_files.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @contact_file = ContactFile.find_by(id: params[:id])

    if @contact_file.nil?
      flash[:error] = "Contact file not found."
      redirect_to contact_files_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = current_user.contacts.order(created_at: :desc).page(params[:page])
  end

  def new
    @contact_file = ContactFile.new
  end

  def create
    @contact_file = current_user.contact_files.build(contact_file_params.merge(status: 'on_hold'))

      if @contact_file.save
        CsvImportJob.perform_later(@contact_file.id, current_user.id)
        redirect_to contacts_path, notice: 'Contacts import has started. Please refresh the page to see the results.'
      else
        render :new
      end
  end

  private

  def contact_file_params
    params.require(:contact_file).permit(:file_name, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact_files/_contact_files.html.erb
<!-- _contact_files.html.erb -->
<h2>Contact Files</h2>
<%= turbo_frame_tag "new_contact_file" do %>
  <%= link_to "New Contact File", new_contact_file_path %>

app/views/contact_files/index.html.erb
<h1>Imported Files</h1>
<table>
  <thead>
    <tr>
      <th>File Name</th>
      <th>Status</th>
      <th>Errors</th>
    </tr>
  </thead>
  <tbody>
    <% @contact_files.each do |contact_file| %>
      <tr>
        <td><%= contact_file.file.filename %></td>
        <td><%= contact_file.status.humanize %></td>
        <td>
          <% if contact_file.error_messages.present? %>
            <%= link_to 'View Errors', contact_file_path(contact_file) %>
          <% else %>
            No errors
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @contact_files %>

app/views/contact_files/show.html.erb
<h2>Contact File: <%= @contact_file.file.filename %></h2>
<h3>Status: <%= @contact_file.status.humanize %></h3>

<% if @contact_file.error_messages.present? %>
  <h4>Error Messages:</h4>
  <ul>
    <% @contact_file.error_messages.each do |error| %>
      <li>
        <%= "Row: #{error[:row].values.join(', ')} - Errors: #{error[:errors].join(', ')}" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No errors found.</p>
<% end %>

app/views/contacts/_contacts.html.erb
<h2>Contacts</h2>
<%= turbo_frame_tag "new_contact" do %>
  <%= link_to "New Contact", new_contact_path %>

app/views/contacts/_contacts_list.html.erb
<%= turbo_frame_tag 'contacts_list' do %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Date of Birth</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Credit Card Number</th>
        <th>Credit Card Network</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.date_of_birth.strftime('%Y %B %d') %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= "**** **** **** #{contact.credit_card_last_four}" %></td>
          <td><%= contact.credit_card_network %></td>
          <td><%= contact.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= paginate @contacts %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<%= link_to 'Import Contacts', new_contact_path, class: 'btn btn-primary', role: 'button', 'aria-disabled': 'false' %>

<div id="contacts-list">
  <%= render 'contacts_list' %>
</div>

<%= turbo_stream_from current_user.contacts %>

app/views/contacts/new.html.erb
<%= turbo_frame_tag "new_contact" do %>
  <% if @errors.present? %>
    <div class="alert alert-danger">
      <h4>Errors while importing contacts:</h4>
        <ul>
          <% @errors.each do |error| %>
            <li>
              <% if error[:row] %>
                <%= "Row: #{error[:row].values.join(', ')} - Errors: #{error[:errors].join(', ')}" %>
              <% else %>
                <%= error[:message] %>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <%= form_with(model: @contact_file, local: true, url: contacts_path, method: :post) do |form| %>
    <div>
      <%= form.label :file_name %>
      <%= form.text_field :file_name %>
    </div>

    <div>
      <%= form.label :file %>
      <%= form.file_field :file %>
    </div>

    <%= button_tag "Upload and Map Columns", type: "submit" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact Import</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header>
    <nav>
      <%= link_to 'Home', root_path %>
      <% if user_signed_in? %>
        <%= link_to 'Contacts', contacts_path %>
        <%= link_to 'Contact Files', contact_files_path %>
        <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete} %>
      <% else %>
        <%= link_to 'Login', new_user_session_path%>
        <%= link_to 'Sign Up', new_user_registration_path%>
      <% end %>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer>
    <!-- Add your footer content here -->
  </footer>
</body>
</html>